linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.3
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: GB
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - hugeParam

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - misspell
    - wsl
    - gomnd

issues:
  # Independently from option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  # Default value for this option is true.
  exclude-use-default: true
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - goimports
        - funlen
        - scopelint
        - wsl

service:
  golangci-lint-version: 1.21.x

