project_name: secure
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  -
    id: "build"
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/pypl-johan/secure/cmd/version.Version={{.Version}} -X github.com/pypl-johan/secure/cmd/version.Commit={{.ShortCommit}} -X github.com/pypl-johan/secure/cmd/version.BuildTime={{.Date}}

